StoreApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('myapp.urls')),
    path('', RedirectView.as_view(url='/products/', permanent=True)),
]

myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.show, name='show'),
]

myapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()

    def __str__(self):
        return self.name

myapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product

def index(request):
    products = Product.objects.all()
    return render(request, 'myapp/index.html', {'products': products})

def show(request, id):
    product = get_object_or_404(Product, pk=id)
    return render(request, 'myapp/show.html', {'product': product})

myapp/templates/myapp/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'myapp/products.css' %}">

<div class="products-index">
  <h1>Products</h1>
  <ul class="product-list">
    {% for product in products %}
      <li class="product-list-item">
        <a href="{% url 'myapp:show' product.id %}" class="product-link">{{ product.name }}</a>
      </li>
    {% endfor %}
  </ul>
</div>

myapp/templates/myapp/show.html
{% load static %}

<link rel="stylesheet" href="{% static 'myapp/products.css' %}">

<div class="products-index">
  <h1 class="product-link">{{ product.name }}</h1>
  <div class="product-price">${{ product.price }}</div>
  <p class="product-description">{{ product.description }}</p>
</div>